'use client';

import { ArrowLeft, ArrowLeftRight, ArrowRight, ArrowUp, Check, ChevronsUp, Copy, ExternalLink, Flame, Fuel, Gamepad2, Gauge, Network, ShieldPlus, Sparkles, Swords, WalletCards, WandSparkles } from 'lucide-react';
import Link from 'next/link';
import { useState } from 'react';

const AQT_ADDRESS = '0xD182A7E85E201412D9f69D98Be3127eC126F05f9';
const FUJI_RPC_URL = 'https://api.avax-test.network/ext/bc/C/rpc';
type EthereumProvider = { request: (request: { method: string; params?: unknown[] }) => Promise<unknown> };
function walletProvider(): EthereumProvider | null { return (window as Window & { ethereum?: EthereumProvider }).ethereum ?? null; }

export function FujiGuide() {
  const [notice, setNotice] = useState('');
  const [copied, setCopied] = useState(false);
  async function copyTokenAddress() { await navigator.clipboard.writeText(AQT_ADDRESS); setCopied(true); setNotice('AQT contract address copied.'); window.setTimeout(() => setCopied(false), 1800); }
  async function addFuji() {
    const provider = walletProvider(); if (!provider) { setNotice('Install MetaMask or Core Wallet first.'); return; }
    try { await provider.request({ method: 'wallet_addEthereumChain', params: [{ chainId: '0xa869', chainName: 'Avalanche Fuji C-Chain', nativeCurrency: { name: 'Avalanche', symbol: 'AVAX', decimals: 18 }, rpcUrls: [FUJI_RPC_URL], blockExplorerUrls: ['https://testnet.snowtrace.io'] }] }); setNotice('Avalanche Fuji is ready.'); } catch { setNotice('The network request was cancelled or could not be completed by your wallet.'); }
  }
  async function addAqt() {
    const provider = walletProvider(); if (!provider) { setNotice('Install MetaMask or Core Wallet first.'); return; }
    try { await provider.request({ method: 'wallet_watchAsset', params: [{ type: 'ERC20', options: { address: AQT_ADDRESS, symbol: 'AQT', decimals: 18 } }] }); setNotice('AQT was added to your wallet token list.'); } catch { setNotice('The AQT registration request was cancelled or could not be completed.'); }
  }
  const setupSteps = [
    { icon: WalletCards, title: 'Connect a wallet', body: 'Prepare MetaMask or Core Wallet, then select Connect Wallet in the header. The connected address must match the address receiving rewards.' },
    { icon: Network, title: 'Switch to Fuji', body: 'Use Avalanche Fuji C-Chain (Chain ID 43113), not Avalanche Mainnet.', action: <button type="button" onClick={() => void addFuji()} className="mt-5 rounded-xl bg-[#9a6728] px-5 py-3 text-xs font-black text-white">ADD OR SWITCH TO FUJI</button> },
    { icon: Fuel, title: 'Get test AVAX', body: 'AVAX pays transaction gas fees. Enter your connected address in the official faucet and request a small amount before playing.', action: <a href="https://core.app/tools/testnet-faucet/" target="_blank" rel="noreferrer" className="mt-5 inline-flex items-center gap-2 rounded-xl border border-[#d8c7ac] bg-white px-5 py-3 text-xs font-black text-[#7f531f]">OFFICIAL FAUCET <ExternalLink size={14} /></a> },
    { icon: Sparkles, title: 'Display AQT', body: 'AQT is earned from stages and spent in shops and upgrade forges. Register the token to see your balance in the wallet.', action: <button type="button" onClick={() => void addAqt()} className="mt-5 rounded-xl bg-[#263f4d] px-5 py-3 text-xs font-black text-white">ADD AQT TO WALLET</button> },
  ];
  const controls = [
    { icon: ArrowLeftRight, keys: ['←', '→'], title: 'Arrow keys · Move', description: 'Move left and right to control distance, reposition for attacks, and leave enemy attack ranges.' },
    { icon: ChevronsUp, keys: ['↑', '↑'], title: 'Up arrow · Double jump', description: 'Press Up to jump and press it once more in the air to double jump onto high platforms or evade boss attacks.' },
    { icon: Gauge, keys: ['Shift'], title: 'Shift · Dash', description: 'Dash quickly in the direction you are facing to escape dangerous areas.' },
    { icon: Swords, keys: ['Space'], title: 'Space · Basic attack', description: 'Use basic attacks to maintain damage while your skills are on cooldown.' },
    { icon: WandSparkles, keys: ['Q', 'W', 'E', 'R'], title: 'Q · W · E · R skills', description: 'Activate class skills when their HUD icons display READY.' },
    { icon: Flame, keys: ['T'], title: 'T · Ultimate', description: 'Use your strongest ability during an important boss phase. Ultimates have long cooldowns.' },
  ];
  return <div>
    <div className="grid gap-4 md:grid-cols-2">{setupSteps.map(({ icon: Icon, title, body, action }, index) => <article key={title} className="rounded-2xl border border-[#e1d6c6] bg-[#faf8f4] p-6 shadow-sm"><div className="flex items-start gap-4"><span className="grid size-11 shrink-0 place-items-center rounded-xl bg-[#efe4d3] text-[#8b5b25]"><Icon size={21} /></span><div><p className="text-[10px] font-black tracking-[.18em] text-[#9a6728]">SETUP {index + 1}</p><h2 className="mt-1 text-lg font-black text-[#201c17]">{title}</h2></div></div><p className="mt-4 text-sm font-medium leading-6 text-[#6f685e]">{body}</p>{action}</article>)}</div>
    <section className="mt-6 rounded-2xl border border-[#d9c59e] bg-[#fffaf0] p-6"><p className="text-[10px] font-black tracking-[.18em] text-[#9a6728]">AQT TOKEN</p><div className="mt-3 flex flex-col gap-3 sm:flex-row sm:items-center"><code className="min-w-0 flex-1 break-all rounded-xl border border-[#cdb78f] bg-white px-4 py-3 text-sm font-black leading-6 text-[#3f2b18] shadow-inner">{AQT_ADDRESS}</code><button type="button" onClick={() => void copyTokenAddress()} className="inline-flex items-center justify-center gap-2 rounded-xl border border-[#cdb78f] bg-white px-5 py-3 text-xs font-black text-[#6f4b22]">{copied ? <Check size={15} /> : <Copy size={15} />}{copied ? 'COPIED' : 'COPY ADDRESS'}</button></div><p className="mt-3 text-xs font-semibold text-[#786b59]">Symbol AQT · 18 decimals · Avalanche Fuji only</p></section>
    <section className="mt-10"><p className="text-[10px] font-black tracking-[.2em] text-[#9a6728]">HOW TO PLAY</p><h2 className="mt-2 text-2xl font-black text-[#201c17]">Combat controls</h2><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{controls.map(({ icon: Icon, keys, title, description }) => <div key={title} className="rounded-xl border border-[#ded6ca] bg-white p-4"><div className="flex items-start justify-between gap-3"><span className="grid size-14 shrink-0 place-items-center rounded-2xl bg-gradient-to-br from-[#f4e7d2] to-[#e4caa1] text-[#835421] shadow-inner"><Icon size={28} strokeWidth={2.4} /></span><div className="flex min-h-9 flex-wrap items-center justify-end gap-1.5">{keys.map((key, index) => <kbd key={`${key}-${index}`} title={`${key} key`} className={`grid h-10 place-items-center rounded-lg border border-[#4b433b] bg-[#201c17] px-2.5 font-mono text-xs font-black text-white shadow-[0_3px_0_#8f8171] ${key === 'Space' ? 'min-w-20' : key === 'Shift' ? 'min-w-16' : 'min-w-10'}`}>{key === '←' ? <ArrowLeft aria-label="Left arrow" size={19} strokeWidth={3} /> : key === '→' ? <ArrowRight aria-label="Right arrow" size={19} strokeWidth={3} /> : key === '↑' ? <ArrowUp aria-label="Up arrow" size={19} strokeWidth={3} /> : key}</kbd>)}</div></div><h3 className="mt-4 text-sm font-black text-[#2d2721]">{title}</h3><p className="mt-2 text-xs font-semibold leading-5 text-[#665e54]">{description}</p></div>)}</div><p className="mt-4 text-sm font-medium leading-6 text-[#766d62]">Skill ranges and effects differ by class. Cast when the HUD icon displays READY, watch boss warning zones and phase changes, and use jumps or dashes to evade. On mobile, use the movement, attack, and skill buttons shown over the game.</p></section>
    <section className="mt-10 grid gap-4 lg:grid-cols-2"><article className="rounded-2xl border border-[#c9d5b4] bg-[#f7faef] p-6"><Sparkles className="text-[#66813d]" /><h2 className="mt-3 text-xl font-black text-[#28321e]">Buying and enhancing skills</h2><ol className="mt-4 list-decimal space-y-2 pl-5 text-sm font-medium leading-6 text-[#5d6850]"><li>Your class starts with its Q skill available. Purchase the remaining class skills from the Skill Altar with AQT.</li><li>Only owned skills can be enhanced. Each enhancement level adds 2 damage and reduces cooldown by 3%, up to +7.</li><li>The enhancement price begins at 20 AQT and doubles after every successful level, so review the displayed price before confirming.</li><li>If approval is required, confirm the AQT approval first and then confirm the enhancement transaction. Keep the page open while either transaction is pending.</li><li>After a successful receipt, verify the new level, damage bonus, cooldown reduction, and AQT balance on the skill card.</li></ol></article><article className="rounded-2xl border border-[#c9d2df] bg-[#f3f7fa] p-6"><ShieldPlus className="text-[#476b87]" /><h2 className="mt-3 text-xl font-black text-[#243542]">Character and armor upgrades</h2><ol className="mt-4 list-decimal space-y-2 pl-5 text-sm font-medium leading-6 text-[#526675]"><li>Open Character Forge and choose Attack, Vitality, or Defense. These are permanent upgrades for the connected account.</li><li>Attack improves outgoing damage, Vitality increases maximum health, and Defense reduces incoming damage as its level rises.</li><li>Check both your AQT balance and Fuji AVAX gas balance before confirming an upgrade.</li><li>Purchase Aegis Armor to equip it and unlock the separate Armor Forge. Armor can be enhanced up to +5.</li><li>Higher armor levels improve protection and make the in-game armor glint more prominent. Wait for SUCCESS before starting another transaction.</li></ol></article></section>
    <section className="mt-6 rounded-2xl border border-[#e3b6b6] bg-[#fff6f4] p-6"><h2 className="font-black text-[#7c302c]">If the faucet displays a warning</h2><p className="mt-2 text-sm font-medium leading-6 text-[#765a56]">The official faucet may enforce account requirements, daily limits, or coupon access. A message requiring a positive Mainnet C-Chain AVAX balance is not a game error. Try the official Builder Hub coupon <strong className="font-black text-[#672b27]">avalanche-academy25</strong>, followed by <strong className="font-black text-[#672b27]">avalanche-academy</strong>. Coupons can expire or become restricted; use the official Avalanche Guild or Discord for current information. You may also transfer a small amount from another test wallet that already holds Fuji AVAX. Never share your private key or recovery phrase.</p><div className="mt-4 flex flex-wrap gap-2"><a href="https://build.avax.network/academy/avalanche-l1/avalanche-fundamentals/04-creating-an-l1/02a-claim-testnet-tokens" target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 rounded-lg border border-[#ddbebe] bg-white px-4 py-2 text-xs font-black text-[#7c302c]">OFFICIAL COUPON GUIDE <ExternalLink size={13} /></a><a href="https://guild.xyz/avalanche" target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 rounded-lg border border-[#ddbebe] bg-white px-4 py-2 text-xs font-black text-[#7c302c]">AVALANCHE GUILD <ExternalLink size={13} /></a></div></section>
    <section className="mt-6 rounded-2xl bg-[#211b18] p-6 text-white"><h2 className="text-xl font-black">From expedition to reward</h2><p className="mt-3 text-sm font-medium leading-6 text-[#d3c8ba]">Choose a class and stage → select Play Now → defeat the boss → wait for server validation → claim AQT → confirm the wallet transaction. Equipment and rare-class drops display a separate NFT mint action.</p></section>
    {notice ? <p role="status" className="mt-5 rounded-xl border border-[#cad8c0] bg-[#f4faef] px-4 py-3 text-sm font-bold text-[#47613a]">{notice}</p> : null}
    <div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link href="/game" className="inline-flex items-center justify-center gap-2 rounded-xl bg-[#211b18] px-7 py-4 text-sm font-black text-white">READY · START THE GAME <Gamepad2 size={17} /></Link><a href={`https://testnet.snowtrace.io/address/${AQT_ADDRESS}`} target="_blank" rel="noreferrer" className="inline-flex items-center justify-center gap-2 rounded-xl border border-[#d8cbb8] px-7 py-4 text-sm font-black text-[#6f4b22]">VIEW AQT CONTRACT <ExternalLink size={16} /></a></div>
  </div>;
}
