'use client';

import { ArrowLeft, ArrowLeftRight, ArrowRight, ArrowUp, Check, ChevronsUp, Copy, ExternalLink, Flame, Fuel, Gamepad2, Gauge, Network, ShieldPlus, Sparkles, Swords, WalletCards, WandSparkles } from 'lucide-react';
import Link from 'next/link';
import { useState } from 'react';

const AQT_ADDRESS = '0xD182A7E85E201412D9f69D98Be3127eC126F05f9';
const FUJI_RPC_URL = 'https://api.avax-test.network/ext/bc/C/rpc';
type EthereumProvider = { request: (request: { method: string; params?: unknown[] }) => Promise<unknown> };
function walletProvider(): EthereumProvider | null { return (window as Window & { ethereum?: EthereumProvider }).ethereum ?? null; }

export function FujiGuide() {
  const [notice, setNotice] = useState('');
  const [copied, setCopied] = useState(false);
  async function copyTokenAddress() { await navigator.clipboard.writeText(AQT_ADDRESS); setCopied(true); setNotice('AQT 컨트랙트 주소를 복사했습니다.'); window.setTimeout(() => setCopied(false), 1800); }
  async function addFuji() {
    const provider = walletProvider(); if (!provider) { setNotice('MetaMask 또는 Core 지갑을 먼저 설치해 주세요.'); return; }
    try { await provider.request({ method: 'wallet_addEthereumChain', params: [{ chainId: '0xa869', chainName: 'Avalanche Fuji C-Chain', nativeCurrency: { name: 'Avalanche', symbol: 'AVAX', decimals: 18 }, rpcUrls: [FUJI_RPC_URL], blockExplorerUrls: ['https://testnet.snowtrace.io'] }] }); setNotice('Avalanche Fuji 네트워크가 준비되었습니다.'); } catch { setNotice('네트워크 추가가 취소되었거나 지갑에서 처리하지 못했습니다.'); }
  }
  async function addAqt() {
    const provider = walletProvider(); if (!provider) { setNotice('MetaMask 또는 Core 지갑을 먼저 설치해 주세요.'); return; }
    try { await provider.request({ method: 'wallet_watchAsset', params: [{ type: 'ERC20', options: { address: AQT_ADDRESS, symbol: 'AQT', decimals: 18 } }] }); setNotice('AQT가 지갑 토큰 목록에 추가되었습니다.'); } catch { setNotice('AQT 등록이 취소되었거나 지갑에서 처리하지 못했습니다.'); }
  }
  const setupSteps = [
    { icon: WalletCards, title: '지갑 연결', body: 'MetaMask 또는 Core 지갑을 준비하고 오른쪽 위 Connect Wallet을 누르세요. 보상 받을 주소와 연결 주소가 같아야 합니다.' },
    { icon: Network, title: 'Fuji로 전환', body: '메인넷이 아닌 Avalanche Fuji C-Chain(Chain ID 43113)을 사용합니다.', action: <button type="button" onClick={() => void addFuji()} className="mt-5 rounded-xl bg-[#9a6728] px-5 py-3 text-xs font-black text-white">FUJI 추가·전환</button> },
    { icon: Fuel, title: '테스트 AVAX 받기', body: 'AVAX는 트랜잭션 가스비입니다. 공식 Faucet에 연결한 주소를 입력해 소량을 먼저 받으세요.', action: <a href="https://core.app/tools/testnet-faucet/" target="_blank" rel="noreferrer" className="mt-5 inline-flex items-center gap-2 rounded-xl border border-[#d8c7ac] bg-white px-5 py-3 text-xs font-black text-[#7f531f]">공식 Faucet <ExternalLink size={14} /></a> },
    { icon: Sparkles, title: 'AQT 토큰 표시', body: 'AQT는 스테이지 보상과 상점에 쓰입니다. 토큰을 등록하면 지갑에서도 잔액을 확인할 수 있습니다.', action: <button type="button" onClick={() => void addAqt()} className="mt-5 rounded-xl bg-[#263f4d] px-5 py-3 text-xs font-black text-white">지갑에 AQT 추가</button> },
  ];
  const controls = [
    { icon: ArrowLeftRight, keys: ['←', '→'], title: '방향키 · 좌우 이동', description: '왼쪽·오른쪽 방향키로 캐릭터를 움직입니다. 적과 거리를 조절하거나 공격 범위를 벗어날 때 사용하세요.' },
    { icon: ChevronsUp, keys: ['↑', '↑'], title: '위 방향키 · 더블 점프', description: '위 방향키를 누르면 점프하고, 공중에서 한 번 더 누르면 더블 점프합니다. 높은 발판과 보스 공격을 피할 수 있습니다.' },
    { icon: Gauge, keys: ['Shift'], title: 'Shift 키 · 대시', description: 'Shift 키를 누르면 바라보는 방향으로 빠르게 이동합니다. 위험 지역에서 즉시 빠져나올 때 사용하세요.' },
    { icon: Swords, keys: ['Space'], title: 'Space 키 · 기본 공격', description: '스페이스바로 기본 공격을 사용합니다. 스킬이 재사용 대기 중일 때 계속 피해를 줄 수 있습니다.' },
    { icon: WandSparkles, keys: ['Q', 'W', 'E', 'R'], title: 'Q·W·E·R 키 · 일반 스킬', description: '각 키로 클래스 고유 스킬을 사용합니다. 화면 하단 아이콘이 READY일 때 발동할 수 있습니다.' },
    { icon: Flame, keys: ['T'], title: 'T 키 · 각성기', description: 'T 키로 가장 강력한 각성기를 사용합니다. 긴 재사용 대기시간을 고려해 보스 페이즈에 맞춰 사용하세요.' },
  ];
  return <div>
    <div className="grid gap-4 md:grid-cols-2">{setupSteps.map(({ icon: Icon, title, body, action }, index) => <article key={title} className="rounded-2xl border border-[#e1d6c6] bg-[#faf8f4] p-6 shadow-sm"><div className="flex items-start gap-4"><span className="grid size-11 shrink-0 place-items-center rounded-xl bg-[#efe4d3] text-[#8b5b25]"><Icon size={21} /></span><div><p className="text-[10px] font-black tracking-[.18em] text-[#9a6728]">SETUP {index + 1}</p><h2 className="mt-1 text-lg font-black text-[#201c17]">{title}</h2></div></div><p className="mt-4 text-sm font-medium leading-6 text-[#6f685e]">{body}</p>{action}</article>)}</div>
    <section className="mt-6 rounded-2xl border border-[#d9c59e] bg-[#fffaf0] p-6"><p className="text-[10px] font-black tracking-[.18em] text-[#9a6728]">AQT TOKEN</p><div className="mt-3 flex flex-col gap-3 sm:flex-row sm:items-center"><code className="min-w-0 flex-1 break-all rounded-xl border border-[#cdb78f] bg-white px-4 py-3 text-sm font-black leading-6 text-[#3f2b18] shadow-inner">{AQT_ADDRESS}</code><button type="button" onClick={() => void copyTokenAddress()} className="inline-flex items-center justify-center gap-2 rounded-xl border border-[#cdb78f] bg-white px-5 py-3 text-xs font-black text-[#6f4b22]">{copied ? <Check size={15} /> : <Copy size={15} />}{copied ? '복사됨' : '주소 복사'}</button></div><p className="mt-3 text-xs font-semibold text-[#786b59]">기호 AQT · 소수점 18 · Avalanche Fuji 전용</p></section>
    <section className="mt-10"><p className="text-[10px] font-black tracking-[.2em] text-[#9a6728]">HOW TO PLAY</p><h2 className="mt-2 text-2xl font-black text-[#201c17]">게임 조작법</h2><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{controls.map(({ icon: Icon, keys, title, description }) => <div key={title} className="rounded-xl border border-[#ded6ca] bg-white p-4"><div className="flex items-start justify-between gap-3"><span className="grid size-14 shrink-0 place-items-center rounded-2xl bg-gradient-to-br from-[#f4e7d2] to-[#e4caa1] text-[#835421] shadow-inner"><Icon size={28} strokeWidth={2.4} /></span><div className="flex min-h-9 flex-wrap items-center justify-end gap-1.5">{keys.map((key, index) => <kbd key={`${key}-${index}`} title={`${key} 키`} className={`grid h-10 place-items-center rounded-lg border border-[#4b433b] bg-[#201c17] px-2.5 font-mono text-xs font-black text-white shadow-[0_3px_0_#8f8171] ${key === 'Space' ? 'min-w-20' : key === 'Shift' ? 'min-w-16' : 'min-w-10'}`}>{key === '←' ? <ArrowLeft aria-label="왼쪽 방향키" size={19} strokeWidth={3} /> : key === '→' ? <ArrowRight aria-label="오른쪽 방향키" size={19} strokeWidth={3} /> : key === '↑' ? <ArrowUp aria-label="위 방향키" size={19} strokeWidth={3} /> : key}</kbd>)}</div></div><h3 className="mt-4 text-sm font-black text-[#2d2721]">{title}</h3><p className="mt-2 text-xs font-semibold leading-5 text-[#665e54]">{description}</p></div>)}</div><p className="mt-4 text-sm font-medium leading-6 text-[#766d62]">스킬의 공격 범위와 효과는 클래스마다 다릅니다. 화면 하단 아이콘이 READY일 때 사용할 수 있고, 보스의 경고 영역과 페이즈 변화를 보고 점프·대시로 회피하세요. 모바일에서는 게임 화면에 표시되는 이동·공격·스킬 버튼을 사용합니다.</p></section>
    <section className="mt-10 grid gap-4 lg:grid-cols-2"><article className="rounded-2xl border border-[#c9d5b4] bg-[#f7faef] p-6"><Sparkles className="text-[#66813d]" /><h2 className="mt-3 text-xl font-black text-[#28321e]">스킬 구매와 강화</h2><ol className="mt-4 list-decimal space-y-2 pl-5 text-sm font-medium leading-6 text-[#5d6850]"><li>처음부터 Q 스킬 1레벨을 사용할 수 있습니다.</li><li>스킬 상점에서 AQT로 W/E/R/T를 구매합니다.</li><li>보유 스킬을 강화하면 공격 성능이 오르고 레벨당 쿨타임도 감소합니다.</li><li>결제 시 AQT 사용 승인과 강화 트랜잭션을 지갑에서 차례로 확인합니다.</li></ol></article><article className="rounded-2xl border border-[#c9d2df] bg-[#f3f7fa] p-6"><ShieldPlus className="text-[#476b87]" /><h2 className="mt-3 text-xl font-black text-[#243542]">캐릭터·방어구 강화</h2><ol className="mt-4 list-decimal space-y-2 pl-5 text-sm font-medium leading-6 text-[#526675]"><li>Character Forge에서 원하는 영구 능력치를 선택합니다.</li><li>AQT 잔액과 Fuji AVAX 가스비를 확인한 뒤 강화합니다.</li><li>방어구를 구매하면 방어구 강화 메뉴가 열립니다.</li><li>pending 중에는 기다리고, success 확인 후 다음 강화를 진행하세요.</li></ol></article></section>
    <section className="mt-6 rounded-2xl border border-[#e3b6b6] bg-[#fff6f4] p-6"><h2 className="font-black text-[#7c302c]">Faucet 경고가 뜬다면</h2><p className="mt-2 text-sm font-medium leading-6 text-[#765a56]">공식 Faucet은 계정 조건, 일일 제한 또는 쿠폰을 요구할 수 있습니다. “메인넷 C-Chain AVAX 잔액이 0보다 커야 함”은 게임 오류가 아닙니다. 쿠폰 입력란에는 Avalanche 공식 Builder Hub 문서가 안내하는 <strong className="font-black text-[#672b27]">avalanche-academy25</strong>를 먼저 사용하고, 되지 않으면 <strong className="font-black text-[#672b27]">avalanche-academy</strong>를 시도하세요. 쿠폰은 만료되거나 제한될 수 있으므로 그때는 네이버·구글에서 “AVAX 테스트넷 쿠폰”을 검색하기보다 공식 Avalanche Guild 또는 Discord에서 최신 쿠폰을 받는 것이 안전합니다. Fuji AVAX가 있는 다른 테스트 지갑에서 소량을 전송하는 방법도 있습니다. 개인키와 복구 문구는 누구에게도 알려주지 마세요.</p><div className="mt-4 flex flex-wrap gap-2"><a href="https://build.avax.network/academy/avalanche-l1/avalanche-fundamentals/04-creating-an-l1/02a-claim-testnet-tokens" target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 rounded-lg border border-[#ddbebe] bg-white px-4 py-2 text-xs font-black text-[#7c302c]">공식 쿠폰 안내 <ExternalLink size={13} /></a><a href="https://guild.xyz/avalanche" target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 rounded-lg border border-[#ddbebe] bg-white px-4 py-2 text-xs font-black text-[#7c302c]">Avalanche Guild <ExternalLink size={13} /></a></div></section>
    <section className="mt-6 rounded-2xl bg-[#211b18] p-6 text-white"><h2 className="text-xl font-black">플레이부터 보상까지</h2><p className="mt-3 text-sm font-medium leading-6 text-[#d3c8ba]">클래스와 스테이지 선택 → Play Now → 보스 처치 → 결과 검증 → Claim AQT → 지갑 트랜잭션 확인 순서입니다. 장비나 희귀 클래스가 드롭되면 별도의 NFT 민팅 버튼이 나타납니다.</p></section>
    {notice ? <p role="status" className="mt-5 rounded-xl border border-[#cad8c0] bg-[#f4faef] px-4 py-3 text-sm font-bold text-[#47613a]">{notice}</p> : null}
    <div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link href="/game" className="inline-flex items-center justify-center gap-2 rounded-xl bg-[#211b18] px-7 py-4 text-sm font-black text-white">준비 완료 · 게임 시작 <Gamepad2 size={17} /></Link><a href={`https://testnet.snowtrace.io/address/${AQT_ADDRESS}`} target="_blank" rel="noreferrer" className="inline-flex items-center justify-center gap-2 rounded-xl border border-[#d8cbb8] px-7 py-4 text-sm font-black text-[#6f4b22]">AQT 컨트랙트 확인 <ExternalLink size={16} /></a></div>
  </div>;
}
